-- =============================================================================
-- PASSO 2/3: CRIAR TABLES (execute DEPOIS do PASSO1)
-- =============================================================================

-- crisis_interventions
CREATE TABLE IF NOT EXISTS crisis_interventions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  level crisis_level NOT NULL,
  types crisis_type[] NOT NULL DEFAULT ARRAY['other']::crisis_type[],
  status intervention_status NOT NULL DEFAULT 'detected',
  trigger_message TEXT,
  matched_patterns TEXT[],
  context_summary TEXT,
  resources_shown TEXT[] DEFAULT ARRAY[]::TEXT[],
  user_actions JSONB DEFAULT '[]'::jsonb,
  follow_up_needed BOOLEAN DEFAULT TRUE,
  follow_up_scheduled_at TIMESTAMPTZ,
  follow_up_completed_at TIMESTAMPTZ,
  follow_up_notes TEXT,
  outcome_notes TEXT,
  resolution_type TEXT,
  session_id UUID,
  app_version TEXT,
  device_info JSONB,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  acknowledged_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  anonymized_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id),
  last_modified_by UUID REFERENCES auth.users(id),
  priority INTEGER DEFAULT 5 CHECK (priority BETWEEN 1 AND 10)
);

-- moderation_queue
CREATE TABLE IF NOT EXISTS moderation_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_id UUID NOT NULL,
  content_type content_type NOT NULL,
  content_text TEXT NOT NULL,
  content_metadata JSONB DEFAULT '{}'::jsonb,
  author_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  author_trust_score DECIMAL(3,2) DEFAULT 5.0,
  author_post_count INTEGER DEFAULT 0,
  author_report_count INTEGER DEFAULT 0,
  source moderation_source NOT NULL,
  status moderation_status NOT NULL DEFAULT 'pending',
  priority INTEGER NOT NULL DEFAULT 5 CHECK (priority BETWEEN 1 AND 10),
  auto_filter_flags TEXT[] DEFAULT ARRAY[]::TEXT[],
  ai_safety_score DECIMAL(3,2),
  ai_analysis JSONB,
  assigned_to UUID REFERENCES auth.users(id),
  assigned_at TIMESTAMPTZ,
  assignment_expires_at TIMESTAMPTZ,
  decision moderation_status,
  decision_reason rejection_reason,
  decision_notes TEXT,
  decided_at TIMESTAMPTZ,
  decided_by UUID REFERENCES auth.users(id),
  escalated_to UUID REFERENCES auth.users(id),
  escalated_at TIMESTAMPTZ,
  escalation_reason TEXT,
  appeal_text TEXT,
  appealed_at TIMESTAMPTZ,
  appeal_decision moderation_status,
  appeal_decided_at TIMESTAMPTZ,
  appeal_decided_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  time_in_queue_ms INTEGER,
  total_review_time_ms INTEGER
);

-- moderators
CREATE TABLE IF NOT EXISTS moderators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  tier TEXT NOT NULL DEFAULT 'base' CHECK (tier IN ('base', 'senior', 'lead', 'founder')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  verified_at TIMESTAMPTZ,
  verified_by UUID REFERENCES auth.users(id),
  compensation_brl DECIMAL(10,2) DEFAULT 300.00,
  payment_info JSONB,
  hours_per_week INTEGER DEFAULT 4,
  available_hours JSONB,
  timezone TEXT DEFAULT 'America/Sao_Paulo',
  stats JSONB DEFAULT '{"total_reviewed": 0, "approved": 0, "rejected": 0, "escalated": 0}'::jsonb,
  training_completed_at TIMESTAMPTZ,
  last_training_at TIMESTAMPTZ,
  certifications TEXT[],
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_active_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

-- moderation_metrics
CREATE TABLE IF NOT EXISTS moderation_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE NOT NULL DEFAULT CURRENT_DATE UNIQUE,
  total_posts INTEGER DEFAULT 0,
  total_queued INTEGER DEFAULT 0,
  auto_approved INTEGER DEFAULT 0,
  auto_blocked INTEGER DEFAULT 0,
  ai_approved INTEGER DEFAULT 0,
  ai_blocked INTEGER DEFAULT 0,
  ai_queued INTEGER DEFAULT 0,
  human_approved INTEGER DEFAULT 0,
  human_rejected INTEGER DEFAULT 0,
  escalated INTEGER DEFAULT 0,
  avg_queue_latency_ms INTEGER,
  p50_queue_latency_ms INTEGER,
  p95_queue_latency_ms INTEGER,
  p99_queue_latency_ms INTEGER,
  false_positive_count INTEGER DEFAULT 0,
  false_negative_count INTEGER DEFAULT 0,
  appeal_count INTEGER DEFAULT 0,
  appeal_success_count INTEGER DEFAULT 0,
  active_moderators INTEGER DEFAULT 0,
  moderator_hours_worked DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

SELECT 'PASSO 2 COMPLETE - Tabelas criadas!' as status;
